Port 3128
Listen 0.0.0.0
Timeout 60
MaxClients 128
Allow 10.248.36.0/24
ConnectPort 443
Filter "/etc/tinyproxy/filter"
FilterURLs On
FilterExtended On
FilterDefaultDeny Yes
DisableViaHeader Yes
LogFile "/tmp/tinyproxy.log"
LogLevel Critical
PidFile "/tmp/tinyproxy.pid"
