import type { ModelFamily, ReasoningTier } from '../data/types.ts';
import type { ExactEfficiencyRow } from './scientific-evidence-resolution.ts';

const publicFamily = {
  Sol: 'sol',
  Terra: 'terra',
  Luna: 'luna',
} as const;

export function configurationWorkbenchFixture({
  id,
  modelFamily = 'Sol',
  reasoningTier = 'low',
  score = 80,
  duration = 100,
  cost = null,
}: {
  id: string;
  modelFamily?: ModelFamily;
  reasoningTier?: ReasoningTier;
  score?: number;
  duration?: number | null;
  cost?: number | null;
}): ExactEfficiencyRow {
  return {
    entry: {
      id,
      modelFamily,
      modelName: `gpt-5.6-${publicFamily[modelFamily]}`,
      reasoningTier,
      score,
      theta: 0,
      standardError: 0.2,
      thetaCiLow: -0.4,
      thetaCiHigh: 0.4,
      scoreCiLow: score - 2,
      scoreCiHigh: score + 2,
      information: 25,
      qualityScore: score,
      strictPassRate: 0.5,
      strictPassLow: 0.4,
      strictPassHigh: 0.6,
      strictPassSampleSize: 72,
      strictPassSuccesses: 36,
      reliabilityStatus: 'single_matrix_information_only',
      calibrationStatus: 'calibrated',
      sensitivityLow: score - 1,
      sensitivityHigh: score + 1,
      sampleSize: 72,
      coveragePercent: 100,
      runtimeIssues: 0,
      missing: 0,
      scoringVersion: '1.0.8',
      scoreStatus: 'official',
      runId: `run-${id}`,
      synthetic: false,
    },
    row: {
      runId: `run-${id}`,
      matrixBatchId: 'batch-1',
      modelFamily: publicFamily[modelFamily],
      reasoningEffort: reasoningTier,
      matrixBatchElapsedMs: 1,
      summedCellAdapterElapsedMs: duration,
      observedMedianWallMs: duration,
      observedP95WallMs: duration,
      observedTimeSampleCount: duration === null ? 0 : 72,
      observedTimeCoveragePercent: duration === null ? 0 : 100,
      durationEvidenceLevel: duration === null ? null : 'runner_observed',
      inputTokens: null,
      cachedInputTokens: null,
      cacheWriteInputTokens: null,
      outputTokens: null,
      reasoningOutputTokens: null,
      totalTokens: null,
      tokenUsageSampleCount: 0,
      tokenUsageSourceLevel: null,
      standardApiEquivalentUsdNanos: cost,
      costEstimatorStatus: cost === null ? 'unavailable_missing_usage' : 'estimated',
      tokenUsageCoveragePercent: cost === null ? null : 100,
      tokenCoverage: {
        input: { count: null, percent: null },
        cachedInput: { count: null, percent: null },
        cacheWriteInput: { count: null, percent: null },
        output: { count: null, percent: null },
        reasoning: { count: null, percent: null },
        total: { count: null, percent: null },
      },
      tokenUsageEvidenceLevel: null,
      costEvidenceLevel: cost === null ? null : 'verifier_recomputed',
      costMethod: null,
      pricingSource: null,
      pricingAsOf: null,
      pricingVersion: null,
      pricingCurrency: cost === null ? null : 'USD',
      pricingProcessingTier: cost === null ? null : 'standard',
      resultCount: 72,
      attemptedResultCount: 72,
      invokedResultCount: 72,
      adapterElapsedObservedResultCount: duration === null ? 0 : 72,
      tokenObservedResultCount: 0,
      pricedResultCount: cost === null ? 0 : 72,
      executionConcurrency: 17,
      estimatedCostSampleCount: cost === null ? 0 : 72,
      costEstimatorLimitations: [],
      pricingRates: [],
      costFormula: null,
    },
  };
}
